cabal-version: 3.4
name: AOC2020
version: 0.1.0.0
-- A short (one-line) description of the package.
-- synopsis:
-- A longer description of the package.
-- description:
-- A URL where users can report bugs.
-- bug-reports:
-- The license under which the package is released.
-- license:
author: alex800121
maintainer: alex800121@hotmail.com
-- A copyright notice.
-- copyright:
-- category:
extra-source-files: CHANGELOG.md

common shared
  default-language: GHC2021
  build-depends:
    AOC,
    array,
    async,
    base >=4.18.0.0,
    base16-bytestring,
    bytestring,
    containers,
    eithers,
    hashable,
    massiv,
    megaparsec,
    multiset,
    parallel,
    parser-combinators,
    pqueue,
    queues,
    split,
    transformers,
    unordered-containers,
    vector,
    wide-word,
    hashtables,

  default-extensions:
    DataKinds
    OverloadedRecordDot
    TypeApplications
    TypeFamilies

  ghc-options: -O2

benchmark main-bench
  type: exitcode-stdio-1.0
  hs-source-dirs: benchmark
  main-is: AOCBench.hs
  build-depends:
    AOC,
    AOC2020,
    base,
    criterion,

  default-language: GHC2021
  -- ghc-options: -O2
  -- ghc-options: -O2 -threaded
  ghc-options:
    -O2
    -threaded
    -rtsopts
    "-with-rtsopts=-N -T"

-- ghc-options: -O2 -threaded +RTS -N
library
  import: shared
  exposed-modules:
    Day1
    Day10
    Day11
    Day12
    Day13
    Day14
    Day15
    Day16
    Day17
    Day18
    Day19
    Day2
    Day20
    Day21
    Day22
    Day23
    Day24
    Day25
    Day3
    Day4
    Day5
    Day6
    Day7
    Day8
    Day9
    Solve

  -- Modules included in this library but not exported.
  other-modules:
    Paths_AOC2020

  -- LANGUAGE extensions used by modules in this package.
  -- other-extensions:
  hs-source-dirs:
    src
    app

executable AOC2020
  import: shared
  main-is: Main.hs
  other-modules:
    Day1
    Day10
    Day11
    Day12
    Day13
    Day14
    Day15
    Day16
    Day17
    Day18
    Day19
    Day2
    Day20
    Day21
    Day22
    Day23
    Day24
    Day25
    Day3
    Day4
    Day5
    Day6
    Day7
    Day8
    Day9
    Paths_AOC2020
    Solve

  -- LANGUAGE extensions used by modules in this package.
  -- other-extensions:
  -- build-depends:
  --     AOC2020
  hs-source-dirs:
    app
    src

  ghc-options:
    -O2
    -threaded
    -rtsopts
    "-with-rtsopts=-N -T"
